;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][WindowOverViewport_11111111]
Pos=0,24
Size=1280,1363
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Beads: biff##beads-biff]
Pos=231,86
Size=972,1087
Collapsed=0
DockId=0x00000001,2

[Window][world_panel]
Pos=592,517
Size=116,172
Collapsed=0

[Window][Biff##biff-session]
Pos=23,97
Size=172,651
Collapsed=0

[Window][Beads: lux##beads-lux]
Pos=231,86
Size=972,1087
Collapsed=0
DockId=0x00000001,4

[Window][biff##biff-session]
Pos=30,40
Size=360,280
Collapsed=0

[Window][Beads: public-website##beads-public-website]
Pos=231,86
Size=972,1087
Collapsed=0
DockId=0x00000001,5

[Window][Beads: ethos##beads-ethos]
Pos=231,86
Size=972,1087
Collapsed=0
DockId=0x00000001,1

[Window][Beads: punt-labs##beads-punt-labs]
Pos=231,86
Size=972,1087
Collapsed=0
DockId=0x00000001,0

[Window][Beads: beadle##beads-beadle]
Pos=231,86
Size=972,1087
Collapsed=0
DockId=0x00000001,3

[Table][0x644C007C,5]

[Table][0x0C5489E0,5]

[Table][0xDE5CDC7D,5]

[Table][0x0F284A4E,5]

[Table][0x315387FF,5]

[Table][0x351C188B,5]

[Docking][Data]
DockNode  ID=0x00000001 Pos=231,86 Size=972,1087 Selected=0xC8774622
DockSpace ID=0x08BD597D Window=0x1BBC0F80 Pos=0,24 Size=1280,1363 CentralNode=1

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
